In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from pandasql import sqldf

sql = lambda q: sqldf(q, globals())


extd_df = pd.read_csv('../data/EXPANDED_acled_covid19.csv')

In [3]:
df = sql('''
SELECT DISTINCT country
FROM extd_df
''')
df

                   country
0                Venezuela
1              South Korea
2                    China
3                   France
4            United States
..                     ...
215         Cayman Islands
216             Montserrat
217  Saint Kitts and Nevis
218               Anguilla
219                 Brunei

[220 rows x 1 columns]

In [14]:
query_fmt = ''
for i, t in enumerate(df['country']):
    t_cln = t.replace(' ', '_')
    t_cln = t_cln.replace('.', '')
    t_cln = t_cln.replace(',', '')
    query_fmt += f'sum(CASE WHEN country = "{t}" THEN 1 ELSE 0 END ) AS "{t_cln}"'
    if i < len(df['country']) - 1:
        query_fmt += ',\n'
        

type_cnt_df = sql(f'''
SELECT source_singular,
{query_fmt}
FROM extd_df
GROUP BY source_singular
''')
type_cnt_df

,source_singular,Venezuela,South_Korea,China,France,United_States,Costa_Rica,Philippines,Germany,Austria,...,Chad,Tanzania,Falkland_Islands,United_Arab_Emirates,Eritrea,Cayman_Islands,Montserrat,Saint_Kitts_and_Nevis,Anguilla,Brunei
0,061.ua,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1 News,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10 Tampa Bay,0,0,0,0,7,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10/11 Now,0,0,0,0,4,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1010WINS,0,0,0,0,15,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5357,net.hr,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5358,news.com.au,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5359,nncMX,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5360,stiripesurse.ro,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5361,yam News,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
tot_cnt_df = sql(f'''
SELECT source_singular,
count(*) total
FROM extd_df
GROUP BY source_singular
''')
tot_cnt_df

      source_singular  total
0              061.ua     10
1              1 News      5
2        10 Tampa Bay      7
3           10/11 Now      4
4            1010WINS     15
...               ...    ...
5357           net.hr     29
5358      news.com.au     23
5359            nncMX     21
5360  stiripesurse.ro      1
5361         yam News      1

[5362 rows x 2 columns]

In [15]:
query_fmt = ''
for i, t in enumerate(df['country']):
    t_cln = t.replace(' ', '_')
    t_cln = t_cln.replace('.', '')
    t_cln = t_cln.replace(',', '')
    t_pct_nm = t_cln + '_pct'
    query_fmt += f'cast({t_cln} AS DOUBLE) / cast(total AS DOUBLE) "{t_pct_nm}"'
    if i < len(df['country']) - 1:
        query_fmt += ',\n'
        
type_pct_df = sql(f'''
SELECT
    a.*,
    b.total,
{query_fmt}
FROM type_cnt_df a
JOIN tot_cnt_df b
    ON a.source_singular = b.source_singular
''')

type_pct_df.to_csv('../data/source_country.csv')

type_pct_df

PandaSQLException: (sqlite3.OperationalError) no such column: Saint
[SQL:
SELECT
    a.*,
    b.total,
cast(Venezuela AS DOUBLE) / cast(total AS DOUBLE) "Venezuela_pct",
cast(South_Korea AS DOUBLE) / cast(total AS DOUBLE) "South_Korea_pct",
cast(China AS DOUBLE) / cast(total AS DOUBLE) "China_pct",
cast(France AS DOUBLE) / cast(total AS DOUBLE) "France_pct",
cast(United_States AS DOUBLE) / cast(total AS DOUBLE) "United_States_pct",
cast(Costa_Rica AS DOUBLE) / cast(total AS DOUBLE) "Costa_Rica_pct",
cast(Philippines AS DOUBLE) / cast(total AS DOUBLE) "Philippines_pct",
cast(Germany AS DOUBLE) / cast(total AS DOUBLE) "Germany_pct",
cast(Austria AS DOUBLE) / cast(total AS DOUBLE) "Austria_pct",
cast(Mauritius AS DOUBLE) / cast(total AS DOUBLE) "Mauritius_pct",
cast(India AS DOUBLE) / cast(total AS DOUBLE) "India_pct",
cast(Honduras AS DOUBLE) / cast(total AS DOUBLE) "Honduras_pct",
cast(United_Kingdom AS DOUBLE) / cast(total AS DOUBLE) "United_Kingdom_pct",
cast(Netherlands AS DOUBLE) / cast(total AS DOUBLE) "Netherlands_pct",
cast(Poland AS DOUBLE) / cast(total AS DOUBLE) "Poland_pct",
cast(Lebanon AS DOUBLE) / cast(total AS DOUBLE) "Lebanon_pct",
cast(Turkey AS DOUBLE) / cast(total AS DOUBLE) "Turkey_pct",
cast(New_Zealand AS DOUBLE) / cast(total AS DOUBLE) "New_Zealand_pct",
cast(Greece AS DOUBLE) / cast(total AS DOUBLE) "Greece_pct",
cast(Mexico AS DOUBLE) / cast(total AS DOUBLE) "Mexico_pct",
cast(Morocco AS DOUBLE) / cast(total AS DOUBLE) "Morocco_pct",
cast(Cyprus AS DOUBLE) / cast(total AS DOUBLE) "Cyprus_pct",
cast(Jordan AS DOUBLE) / cast(total AS DOUBLE) "Jordan_pct",
cast(Peru AS DOUBLE) / cast(total AS DOUBLE) "Peru_pct",
cast(Canada AS DOUBLE) / cast(total AS DOUBLE) "Canada_pct",
cast(Bolivia AS DOUBLE) / cast(total AS DOUBLE) "Bolivia_pct",
cast(Nepal AS DOUBLE) / cast(total AS DOUBLE) "Nepal_pct",
cast(Italy AS DOUBLE) / cast(total AS DOUBLE) "Italy_pct",
cast(Chile AS DOUBLE) / cast(total AS DOUBLE) "Chile_pct",
cast(Saint_Vincent_and_the_Grenadines AS DOUBLE) / cast(total AS DOUBLE) "Saint_Vincent_and_the_Grenadines_pct",
cast(Kyrgyzstan AS DOUBLE) / cast(total AS DOUBLE) "Kyrgyzstan_pct",
cast(Cape_Verde AS DOUBLE) / cast(total AS DOUBLE) "Cape_Verde_pct",
cast(Taiwan AS DOUBLE) / cast(total AS DOUBLE) "Taiwan_pct",
cast(Mali AS DOUBLE) / cast(total AS DOUBLE) "Mali_pct",
cast(South_Africa AS DOUBLE) / cast(total AS DOUBLE) "South_Africa_pct",
cast(Kazakhstan AS DOUBLE) / cast(total AS DOUBLE) "Kazakhstan_pct",
cast(Uruguay AS DOUBLE) / cast(total AS DOUBLE) "Uruguay_pct",
cast(North_Korea AS DOUBLE) / cast(total AS DOUBLE) "North_Korea_pct",
cast(Israel AS DOUBLE) / cast(total AS DOUBLE) "Israel_pct",
cast(Kosovo AS DOUBLE) / cast(total AS DOUBLE) "Kosovo_pct",
cast(Mongolia AS DOUBLE) / cast(total AS DOUBLE) "Mongolia_pct",
cast(Romania AS DOUBLE) / cast(total AS DOUBLE) "Romania_pct",
cast(Indonesia AS DOUBLE) / cast(total AS DOUBLE) "Indonesia_pct",
cast(Guadeloupe AS DOUBLE) / cast(total AS DOUBLE) "Guadeloupe_pct",
cast(Russia AS DOUBLE) / cast(total AS DOUBLE) "Russia_pct",
cast(Suriname AS DOUBLE) / cast(total AS DOUBLE) "Suriname_pct",
cast(Japan AS DOUBLE) / cast(total AS DOUBLE) "Japan_pct",
cast(Algeria AS DOUBLE) / cast(total AS DOUBLE) "Algeria_pct",
cast(El_Salvador AS DOUBLE) / cast(total AS DOUBLE) "El_Salvador_pct",
cast(Iran AS DOUBLE) / cast(total AS DOUBLE) "Iran_pct",
cast(Spain AS DOUBLE) / cast(total AS DOUBLE) "Spain_pct",
cast(Guatemala AS DOUBLE) / cast(total AS DOUBLE) "Guatemala_pct",
cast(Belgium AS DOUBLE) / cast(total AS DOUBLE) "Belgium_pct",
cast(Argentina AS DOUBLE) / cast(total AS DOUBLE) "Argentina_pct",
cast(Nauru AS DOUBLE) / cast(total AS DOUBLE) "Nauru_pct",
cast(American_Samoa AS DOUBLE) / cast(total AS DOUBLE) "American_Samoa_pct",
cast(Paraguay AS DOUBLE) / cast(total AS DOUBLE) "Paraguay_pct",
cast(Portugal AS DOUBLE) / cast(total AS DOUBLE) "Portugal_pct",
cast(Rwanda AS DOUBLE) / cast(total AS DOUBLE) "Rwanda_pct",
cast(Trinidad_and_Tobago AS DOUBLE) / cast(total AS DOUBLE) "Trinidad_and_Tobago_pct",
cast(Madagascar AS DOUBLE) / cast(total AS DOUBLE) "Madagascar_pct",
cast(Vanuatu AS DOUBLE) / cast(total AS DOUBLE) "Vanuatu_pct",
cast(Ireland AS DOUBLE) / cast(total AS DOUBLE) "Ireland_pct",
cast(Brazil AS DOUBLE) / cast(total AS DOUBLE) "Brazil_pct",
cast(Australia AS DOUBLE) / cast(total AS DOUBLE) "Australia_pct",
cast(Pakistan AS DOUBLE) / cast(total AS DOUBLE) "Pakistan_pct",
cast(Mauritania AS DOUBLE) / cast(total AS DOUBLE) "Mauritania_pct",
cast(Singapore AS DOUBLE) / cast(total AS DOUBLE) "Singapore_pct",
cast(Tunisia AS DOUBLE) / cast(total AS DOUBLE) "Tunisia_pct",
cast(Martinique AS DOUBLE) / cast(total AS DOUBLE) "Martinique_pct",
cast(Bangladesh AS DOUBLE) / cast(total AS DOUBLE) "Bangladesh_pct",
cast(Caribbean_Netherlands AS DOUBLE) / cast(total AS DOUBLE) "Caribbean_Netherlands_pct",
cast(Bulgaria AS DOUBLE) / cast(total AS DOUBLE) "Bulgaria_pct",
cast(Malaysia AS DOUBLE) / cast(total AS DOUBLE) "Malaysia_pct",
cast(Sudan AS DOUBLE) / cast(total AS DOUBLE) "Sudan_pct",
cast(Ghana AS DOUBLE) / cast(total AS DOUBLE) "Ghana_pct",
cast(Hungary AS DOUBLE) / cast(total AS DOUBLE) "Hungary_pct",
cast(Ecuador AS DOUBLE) / cast(total AS DOUBLE) "Ecuador_pct",
cast(Panama AS DOUBLE) / cast(total AS DOUBLE) "Panama_pct",
cast(Equatorial_Guinea AS DOUBLE) / cast(total AS DOUBLE) "Equatorial_Guinea_pct",
cast(Finland AS DOUBLE) / cast(total AS DOUBLE) "Finland_pct",
cast(Samoa AS DOUBLE) / cast(total AS DOUBLE) "Samoa_pct",
cast(Zimbabwe AS DOUBLE) / cast(total AS DOUBLE) "Zimbabwe_pct",
cast(Afghanistan AS DOUBLE) / cast(total AS DOUBLE) "Afghanistan_pct",
cast(Thailand AS DOUBLE) / cast(total AS DOUBLE) "Thailand_pct",
cast(Serbia AS DOUBLE) / cast(total AS DOUBLE) "Serbia_pct",
cast(Sri_Lanka AS DOUBLE) / cast(total AS DOUBLE) "Sri_Lanka_pct",
cast(New_Caledonia AS DOUBLE) / cast(total AS DOUBLE) "New_Caledonia_pct",
cast(Benin AS DOUBLE) / cast(total AS DOUBLE) "Benin_pct",
cast(Croatia AS DOUBLE) / cast(total AS DOUBLE) "Croatia_pct",
cast(Estonia AS DOUBLE) / cast(total AS DOUBLE) "Estonia_pct",
cast(Kenya AS DOUBLE) / cast(total AS DOUBLE) "Kenya_pct",
cast(French_Polynesia AS DOUBLE) / cast(total AS DOUBLE) "French_Polynesia_pct",
cast(Norway AS DOUBLE) / cast(total AS DOUBLE) "Norway_pct",
cast(Czech_Republic AS DOUBLE) / cast(total AS DOUBLE) "Czech_Republic_pct",
cast(Ukraine AS DOUBLE) / cast(total AS DOUBLE) "Ukraine_pct",
cast(Iraq AS DOUBLE) / cast(total AS DOUBLE) "Iraq_pct",
cast(North_Macedonia AS DOUBLE) / cast(total AS DOUBLE) "North_Macedonia_pct",
cast(Sweden AS DOUBLE) / cast(total AS DOUBLE) "Sweden_pct",
cast(Switzerland AS DOUBLE) / cast(total AS DOUBLE) "Switzerland_pct",
cast(French_Guiana AS DOUBLE) / cast(total AS DOUBLE) "French_Guiana_pct",
cast(Moldova AS DOUBLE) / cast(total AS DOUBLE) "Moldova_pct",
cast(Dominican_Republic AS DOUBLE) / cast(total AS DOUBLE) "Dominican_Republic_pct",
cast(Latvia AS DOUBLE) / cast(total AS DOUBLE) "Latvia_pct",
cast(Montenegro AS DOUBLE) / cast(total AS DOUBLE) "Montenegro_pct",
cast(Georgia AS DOUBLE) / cast(total AS DOUBLE) "Georgia_pct",
cast(Slovenia AS DOUBLE) / cast(total AS DOUBLE) "Slovenia_pct",
cast(Bermuda AS DOUBLE) / cast(total AS DOUBLE) "Bermuda_pct",
cast(Luxembourg AS DOUBLE) / cast(total AS DOUBLE) "Luxembourg_pct",
cast(Cambodia AS DOUBLE) / cast(total AS DOUBLE) "Cambodia_pct",
cast(Belarus AS DOUBLE) / cast(total AS DOUBLE) "Belarus_pct",
cast(Colombia AS DOUBLE) / cast(total AS DOUBLE) "Colombia_pct",
cast(Tonga AS DOUBLE) / cast(total AS DOUBLE) "Tonga_pct",
cast(Solomon_Islands AS DOUBLE) / cast(total AS DOUBLE) "Solomon_Islands_pct",
cast(Saint_Pierre_and_Miquelon AS DOUBLE) / cast(total AS DOUBLE) "Saint_Pierre_and_Miquelon_pct",
cast(Denmark AS DOUBLE) / cast(total AS DOUBLE) "Denmark_pct",
cast(Slovakia AS DOUBLE) / cast(total AS DOUBLE) "Slovakia_pct",
cast(Bailiwick_of_Guernsey AS DOUBLE) / cast(total AS DOUBLE) "Bailiwick_of_Guernsey_pct",
cast(Malta AS DOUBLE) / cast(total AS DOUBLE) "Malta_pct",
cast(Reunion AS DOUBLE) / cast(total AS DOUBLE) "Reunion_pct",
cast(Vietnam AS DOUBLE) / cast(total AS DOUBLE) "Vietnam_pct",
cast(San_Marino AS DOUBLE) / cast(total AS DOUBLE) "San_Marino_pct",
cast(Armenia AS DOUBLE) / cast(total AS DOUBLE) "Armenia_pct",
cast(Liechtenstein AS DOUBLE) / cast(total AS DOUBLE) "Liechtenstein_pct",
cast(Puerto_Rico AS DOUBLE) / cast(total AS DOUBLE) "Puerto_Rico_pct",
cast(Papua_New_Guinea AS DOUBLE) / cast(total AS DOUBLE) "Papua_New_Guinea_pct",
cast(Malawi AS DOUBLE) / cast(total AS DOUBLE) "Malawi_pct",
cast(Lithuania AS DOUBLE) / cast(total AS DOUBLE) "Lithuania_pct",
cast(Uganda AS DOUBLE) / cast(total AS DOUBLE) "Uganda_pct",
cast(Maldives AS DOUBLE) / cast(total AS DOUBLE) "Maldives_pct",
cast(Albania AS DOUBLE) / cast(total AS DOUBLE) "Albania_pct",
cast(Aruba AS DOUBLE) / cast(total AS DOUBLE) "Aruba_pct",
cast(Antigua_and_Barbuda AS DOUBLE) / cast(total AS DOUBLE) "Antigua_and_Barbuda_pct",
cast(Monaco AS DOUBLE) / cast(total AS DOUBLE) "Monaco_pct",
cast(Jamaica AS DOUBLE) / cast(total AS DOUBLE) "Jamaica_pct",
cast(Iceland AS DOUBLE) / cast(total AS DOUBLE) "Iceland_pct",
cast(Nigeria AS DOUBLE) / cast(total AS DOUBLE) "Nigeria_pct",
cast(Cook_Islands AS DOUBLE) / cast(total AS DOUBLE) "Cook_Islands_pct",
cast(Libya AS DOUBLE) / cast(total AS DOUBLE) "Libya_pct",
cast(Saint-Martin AS DOUBLE) / cast(total AS DOUBLE) "Saint-Martin_pct",
cast(Fiji AS DOUBLE) / cast(total AS DOUBLE) "Fiji_pct",
cast(Yemen AS DOUBLE) / cast(total AS DOUBLE) "Yemen_pct",
cast(Guam AS DOUBLE) / cast(total AS DOUBLE) "Guam_pct",
cast(eSwatini AS DOUBLE) / cast(total AS DOUBLE) "eSwatini_pct",
cast(Andorra AS DOUBLE) / cast(total AS DOUBLE) "Andorra_pct",
cast(Bosnia_and_Herzegovina AS DOUBLE) / cast(total AS DOUBLE) "Bosnia_and_Herzegovina_pct",
cast(Gabon AS DOUBLE) / cast(total AS DOUBLE) "Gabon_pct",
cast(Sint_Maarten AS DOUBLE) / cast(total AS DOUBLE) "Sint_Maarten_pct",
cast(Syria AS DOUBLE) / cast(total AS DOUBLE) "Syria_pct",
cast(Wallis_and_Futuna AS DOUBLE) / cast(total AS DOUBLE) "Wallis_and_Futuna_pct",
cast(Grenada AS DOUBLE) / cast(total AS DOUBLE) "Grenada_pct",
cast(Mozambique AS DOUBLE) / cast(total AS DOUBLE) "Mozambique_pct",
cast(Myanmar AS DOUBLE) / cast(total AS DOUBLE) "Myanmar_pct",
cast(Togo AS DOUBLE) / cast(total AS DOUBLE) "Togo_pct",
cast(Democratic_Republic_of_Congo AS DOUBLE) / cast(total AS DOUBLE) "Democratic_Republic_of_Congo_pct",
cast(Guinea-Bissau AS DOUBLE) / cast(total AS DOUBLE) "Guinea-Bissau_pct",
cast(Niger AS DOUBLE) / cast(total AS DOUBLE) "Niger_pct",
cast(Palestine AS DOUBLE) / cast(total AS DOUBLE) "Palestine_pct",
cast(Cameroon AS DOUBLE) / cast(total AS DOUBLE) "Cameroon_pct",
cast(Belize AS DOUBLE) / cast(total AS DOUBLE) "Belize_pct",
cast(Guyana AS DOUBLE) / cast(total AS DOUBLE) "Guyana_pct",
cast(Cuba AS DOUBLE) / cast(total AS DOUBLE) "Cuba_pct",
cast(Namibia AS DOUBLE) / cast(total AS DOUBLE) "Namibia_pct",
cast(Angola AS DOUBLE) / cast(total AS DOUBLE) "Angola_pct",
cast(Ivory_Coast AS DOUBLE) / cast(total AS DOUBLE) "Ivory_Coast_pct",
cast(Senegal AS DOUBLE) / cast(total AS DOUBLE) "Senegal_pct",
cast(Barbados AS DOUBLE) / cast(total AS DOUBLE) "Barbados_pct",
cast(Bailiwick_of_Jersey AS DOUBLE) / cast(total AS DOUBLE) "Bailiwick_of_Jersey_pct",
cast(Laos AS DOUBLE) / cast(total AS DOUBLE) "Laos_pct",
cast(Liberia AS DOUBLE) / cast(total AS DOUBLE) "Liberia_pct",
cast(Isle_of_Man AS DOUBLE) / cast(total AS DOUBLE) "Isle_of_Man_pct",
cast(Bahrain AS DOUBLE) / cast(total AS DOUBLE) "Bahrain_pct",
cast(Gibraltar AS DOUBLE) / cast(total AS DOUBLE) "Gibraltar_pct",
cast(Nicaragua AS DOUBLE) / cast(total AS DOUBLE) "Nicaragua_pct",
cast(Kuwait AS DOUBLE) / cast(total AS DOUBLE) "Kuwait_pct",
cast(Northern_Mariana_Islands AS DOUBLE) / cast(total AS DOUBLE) "Northern_Mariana_Islands_pct",
cast(Bahamas AS DOUBLE) / cast(total AS DOUBLE) "Bahamas_pct",
cast(Egypt AS DOUBLE) / cast(total AS DOUBLE) "Egypt_pct",
cast(Haiti AS DOUBLE) / cast(total AS DOUBLE) "Haiti_pct",
cast(Curacao AS DOUBLE) / cast(total AS DOUBLE) "Curacao_pct",
cast(Virgin_Islands_US AS DOUBLE) / cast(total AS DOUBLE) "Virgin_Islands_US_pct",
cast(Azerbaijan AS DOUBLE) / cast(total AS DOUBLE) "Azerbaijan_pct",
cast(Guinea AS DOUBLE) / cast(total AS DOUBLE) "Guinea_pct",
cast(Botswana AS DOUBLE) / cast(total AS DOUBLE) "Botswana_pct",
cast(Dominica AS DOUBLE) / cast(total AS DOUBLE) "Dominica_pct",
cast(East_Timor AS DOUBLE) / cast(total AS DOUBLE) "East_Timor_pct",
cast(South_Sudan AS DOUBLE) / cast(total AS DOUBLE) "South_Sudan_pct",
cast(Uzbekistan AS DOUBLE) / cast(total AS DOUBLE) "Uzbekistan_pct",
cast(Saint_Lucia AS DOUBLE) / cast(total AS DOUBLE) "Saint_Lucia_pct",
cast(Somalia AS DOUBLE) / cast(total AS DOUBLE) "Somalia_pct",
cast(Lesotho AS DOUBLE) / cast(total AS DOUBLE) "Lesotho_pct",
cast(Saint-Barthelemy AS DOUBLE) / cast(total AS DOUBLE) "Saint-Barthelemy_pct",
cast(Zambia AS DOUBLE) / cast(total AS DOUBLE) "Zambia_pct",
cast(Turks_and_Caicos_Islands AS DOUBLE) / cast(total AS DOUBLE) "Turks_and_Caicos_Islands_pct",
cast(Burundi AS DOUBLE) / cast(total AS DOUBLE) "Burundi_pct",
cast(Republic_of_Congo AS DOUBLE) / cast(total AS DOUBLE) "Republic_of_Congo_pct",
cast(Seychelles AS DOUBLE) / cast(total AS DOUBLE) "Seychelles_pct",
cast(Oman AS DOUBLE) / cast(total AS DOUBLE) "Oman_pct",
cast(Saudi_Arabia AS DOUBLE) / cast(total AS DOUBLE) "Saudi_Arabia_pct",
cast(Ethiopia AS DOUBLE) / cast(total AS DOUBLE) "Ethiopia_pct",
cast(Saint_Helena_Ascension_and_Tristan_da_Cunha AS DOUBLE) / cast(total AS DOUBLE) "Saint_Helena_Ascension_and_Tristan_da_Cunha_pct",
cast(Gambia AS DOUBLE) / cast(total AS DOUBLE) "Gambia_pct",
cast(Central_African_Republic AS DOUBLE) / cast(total AS DOUBLE) "Central_African_Republic_pct",
cast(Djibouti AS DOUBLE) / cast(total AS DOUBLE) "Djibouti_pct",
cast(Bhutan AS DOUBLE) / cast(total AS DOUBLE) "Bhutan_pct",
cast(Tajikistan AS DOUBLE) / cast(total AS DOUBLE) "Tajikistan_pct",
cast(Sierra_Leone AS DOUBLE) / cast(total AS DOUBLE) "Sierra_Leone_pct",
cast(Turkmenistan AS DOUBLE) / cast(total AS DOUBLE) "Turkmenistan_pct",
cast(Qatar AS DOUBLE) / cast(total AS DOUBLE) "Qatar_pct",
cast(Burkina_Faso AS DOUBLE) / cast(total AS DOUBLE) "Burkina_Faso_pct",
cast(Chad AS DOUBLE) / cast(total AS DOUBLE) "Chad_pct",
cast(Tanzania AS DOUBLE) / cast(total AS DOUBLE) "Tanzania_pct",
cast(Falkland_Islands AS DOUBLE) / cast(total AS DOUBLE) "Falkland_Islands_pct",
cast(United_Arab_Emirates AS DOUBLE) / cast(total AS DOUBLE) "United_Arab_Emirates_pct",
cast(Eritrea AS DOUBLE) / cast(total AS DOUBLE) "Eritrea_pct",
cast(Cayman_Islands AS DOUBLE) / cast(total AS DOUBLE) "Cayman_Islands_pct",
cast(Montserrat AS DOUBLE) / cast(total AS DOUBLE) "Montserrat_pct",
cast(Saint_Kitts_and_Nevis AS DOUBLE) / cast(total AS DOUBLE) "Saint_Kitts_and_Nevis_pct",
cast(Anguilla AS DOUBLE) / cast(total AS DOUBLE) "Anguilla_pct",
cast(Brunei AS DOUBLE) / cast(total AS DOUBLE) "Brunei_pct"
FROM type_cnt_df a
JOIN tot_cnt_df b
    ON a.source_singular = b.source_singular
]
(Background on this error at: https://sqlalche.me/e/14/e3q8)